[package]
name = "quick-accent"
version = "0.1.0"
edition = "2024"

[dependencies]
ron = "0.10.1"
serde = { version = "1.0.157", features = ["derive"] }

[dependencies.iced]
git = "https://github.com/iced-rs/iced"
# features = ["tokio", "advanced"]
