[package]
name = "quick-accent"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"

[dependencies.iced]
git = "https://github.com/iced-rs/iced"
# features = ["tokio", "advanced"]
